### ISSUE TITLE
1.4.0 release checklist

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/amqp091-go#77]
- [x] - Fix flaky tests - #75, #85
- [x] - Fix lint errors - #78 
- [x] - Provide a logging interface - #81 (requires bumping to 1.4.0)
